export output_dir="./sst2/qlora"
python /home/lab/bumjun/low_rank/examples/NLU/examples/text-classification/run_glue_qlora.py \
--model_name_or_path huggyllama/llama-7b \
--task_name sst2 \
--do_train \
--do_eval \
--max_seq_length 64 \
--per_device_train_batch_size 1 \
--per_device_eval_batch_size 1 \
--gradient_accumulation_steps 32 \
--learning_rate 4e-4 \
--warmup_ratio 0.06 \
--num_train_epochs 1 \
--output_dir $output_dir/model \
--logging_dir $output_dir/log \
--overwrite_output_dir \
--logging_steps 10 \
--fp16 \
--fp16_opt_level O2 \
--fp16_full_eval \
--save_total_limit 1 \
--eval_steps 400 \
--evaluation_strategy steps \
--save_steps 1200 \
--apply_lora \
--lora_r 8 \
--lora_alpha 8 \
--seed 0 \
--weight_decay 0.1 \
--push_to_hub \
--ex_type ft_with_lora_llama7b